version: "3.5"

services:
  sparkjob:
    image: vedsted/spark_executor
    container_name: spark-csv-to-df
    volumes:
      - ./app.py:/app/app.py

networks:
  default:
    external:
      name: hadoop