version: "3.5"

services:
  sparkjob:
    image: vedsted/spark_local
    container_name: spark-push-csv
    volumes:
      - ./app.py:/app/app.py
      - ./files:/app/files

networks:
  default:
    external:
      name: hadoop